Build linux packages files and push to respective repos
iits-consulting/otc-auth pull request #39
Opened 2023-06-26 16:40 UTC by Ninja243

Creates github action to build linux packages files and push them to the repos here: 
 - https://github.com/iits-consulting/ppa
 - https://github.com/iits-consulting/apk-repo
 - https://github.com/iits-consulting/rpm-repo

Closes https://github.com/iits-consulting/otc-auth/issues/25

2023-07-12 12:14 UTC, Ninja243 commented
PR to homebrew: https://github.com/Homebrew/homebrew-core/pull/136413

2023-07-19 06:38 UTC, zeljkobekcic commented on .goreleaser.yaml
> +    description: "Test"
Maybe we should change just this here

2023-07-19 06:47 UTC, zeljkobekcic submitted a review, later dismissed
There is just one "Test" in the .goreleaser.yaml. I am ATM not sure what it means

2023-07-27 12:44 UTC, Ninja243 commented
> There is just one "Test" in the .goreleaser.yaml. I am ATM not sure what it means

Good spot, I missed that. It refers to the app's description: https://goreleaser.com/customization/nfpm

2023-08-23 07:16 UTC, zeljkobekcic requested changes

2023-08-23 07:16 UTC, zeljkobekcic commented on Formula/otc-auth.rb
> +  license "MIT"
Just make it GPLv3 and we are good to go!
https://github.com/iits-consulting/otc-auth/blob/main/LICENSE

2023-08-25 12:41 UTC, zeljkobekcic approved these changes

2023-09-18 08:38 UTC, merged